FROM composer:2.7 AS composer

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install --no-dev --optimize-autoloader --no-interaction

FROM hyperf/hyperf:8.4-alpine-v3.21-swoole-slim

WORKDIR /var/www

COPY . /var/www

COPY --from=composer /app/vendor /var/www/vendor

EXPOSE 9051

ENTRYPOINT ["php", "index.php", "start"]